*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º 02/09/94            GETORDER.SPR               22:22:22 º
*       º                                                         º
*       ÇÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¶
*       º                                                         º
*       º Author's Name                                           º
*       º                                                         º
*       º Copyright (c) 1994 Company Name                         º
*       º Address                                                 º
*       º City,     Zip                                           º
*       º                                                         º
*       º Description:                                            º
*       º This program was automatically generated by GENSCRN.    º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½

DO CASE
CASE _DOS OR _UNIX      && no UNIX records in screen

	
	#REGION 0
	REGIONAL m.currarea, m.talkstat, m.compstat
	
	IF SET("TALK") = "ON"
		SET TALK OFF
		m.talkstat = "ON"
	ELSE
		m.talkstat = "OFF"
	ENDIF
	m.compstat = SET("COMPATIBLE")
	SET COMPATIBLE FOXPLUS
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º                MS-DOS Window definitions                º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	IF NOT WEXIST("_qne1byaz8")
		DEFINE WINDOW _qne1byaz8 ;
			FROM INT((SROW()-7)/2),INT((SCOL()-42)/2) ;
			TO INT((SROW()-7)/2)+6,INT((SCOL()-42)/2)+41 ;
			TITLE "Index Order" ;
			FLOAT ;
			NOCLOSE ;
			SHADOW ;
			NOMINIMIZE ;
			DOUBLE ;
			COLOR SCHEME 5
	ENDIF
	
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º         GETORDER/MS-DOS Setup Code - SECTION 2          º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	#REGION 1
	skipvar = .T.
	
	IF TYPE("tagnum") = "U"
	   PUBLIC tagnum
	   tagnum = 1
	ENDIF
	
	m.startord = ORDER()
	m.startalias = ALIAS()
	
	SET ORDER TO 0
	numtag = 1
	DO WHILE "" <> TAG(numtag)
	   numtag = numtag + 1
	ENDDO
	
	DIMENSION idxtags(numtag-1)
	i = 1
	DO WHILE i <= numtag-1
	   idxtags[i] = TAG(i)
	   i = i + 1
	ENDDO
	SET ORDER TO (m.startord)
	
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º              GETORDER/MS-DOS Screen Layout              º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	#REGION 1
	IF WVISIBLE("_qne1byaz8")
		ACTIVATE WINDOW _qne1byaz8 SAME
	ELSE
		ACTIVATE WINDOW _qne1byaz8 NOSHOW
	ENDIF
	@ 0,15 GET tagnum ;
		PICTURE "@^" ;
		FROM idxtags ;
		SIZE 3,23 ;
		DEFAULT 1 ;
		COLOR SCHEME 5, 6
	@ 1,2 SAY "Index Order:" ;
		SIZE 1,12, 0
	@ 4,9 GET ordbut ;
		PICTURE "@*HT \!OK;\?Cancel" ;
		SIZE 1,10,2 ;
		DEFAULT 1
	
	IF NOT WVISIBLE("_qne1byaz8")
		ACTIVATE WINDOW _qne1byaz8
	ENDIF
	
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º    MS-DOSREAD contains clauses from SCREEN getorder     º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	READ CYCLE ;
		ACTIVATE _qne1bybp5() ;
		DEACTIVATE _qne1bybqt() ;
		MODAL
	
	RELEASE WINDOW _qne1byaz8
	
	#REGION 0
	IF m.talkstat = "ON"
		SET TALK ON
	ENDIF
	IF m.compstat = "ON"
		SET COMPATIBLE ON
	ENDIF
	
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º              GETORDER/MS-DOS Cleanup Code               º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	#REGION 1
	skipvar = .F.
	IF ordbut = 1
	   SET ORDER TO TAG(tagnum)
	ELSE
	   SET ORDER TO (m.startord)
	   m.tagnum = m.startord
	ENDIF
	SHOW GETS
	

CASE _MAC

	
	#REGION 0
	REGIONAL m.currarea, m.talkstat, m.compstat
	
	IF SET("TALK") = "ON"
		SET TALK OFF
		m.talkstat = "ON"
	ELSE
		m.talkstat = "OFF"
	ENDIF
	m.compstat = SET("COMPATIBLE")
	SET COMPATIBLE FOXPLUS
	
	m.rborder = SET("READBORDER")
	SET READBORDER OFF
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º              Macintosh Window definitions               º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	IF NOT WEXIST("_qne1byc3z")
		DEFINE WINDOW _qne1byc3z ;
			AT  0.000, 0.000  ;
			SIZE 6.385,41.500 ;
			TITLE "Index Order" ;
			FONT "Geneva", 10 ;
			FLOAT ;
			NOCLOSE ;
			SHADOW ;
			DOUBLE
		MOVE WINDOW _qne1byc3z CENTER
	ENDIF
	
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º        GETORDER/Macintosh Setup Code - SECTION 2        º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	#REGION 1
	skipvar = .T.
	
	IF TYPE("tagnum") = "U"
	   PUBLIC tagnum
	   tagnum = 1
	ENDIF
	
	m.startord = ORDER()
	m.startalias = ALIAS()
	
	SET ORDER TO 0
	numtag = 1
	DO WHILE "" <> TAG(numtag)
	   numtag = numtag + 1
	ENDDO
	
	DIMENSION idxtags(numtag-1)
	i = 1
	DO WHILE i <= numtag-1
	   idxtags[i] = TAG(i)
	   i = i + 1
	ENDDO
	SET ORDER TO (m.startord)
	
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º            GETORDER/Macintosh Screen Layout             º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	#REGION 1
	IF WVISIBLE("_qne1byc3z")
		ACTIVATE WINDOW _qne1byc3z SAME
	ELSE
		ACTIVATE WINDOW _qne1byc3z NOSHOW
	ENDIF
	@ 1.154,16.500 GET tagnum ;
		PICTURE "@^3" ;
		FROM idxtags ;
		SIZE 1.462,23.333 ;
		DEFAULT 1 ;
		FONT "Geneva", 10
	@ 4.000,7.500 GET ordbut ;
		PICTURE "@*HT3 \!OK;\?Cancel" ;
		SIZE 1.462,10.714,2.143 ;
		DEFAULT 1 ;
		FONT "Geneva", 10 ;
		STYLE "B"
	@ 1.462,3.333 SAY "Index Order:"  ;
		FONT "Geneva", 10
	
	IF NOT WVISIBLE("_qne1byc3z")
		ACTIVATE WINDOW _qne1byc3z
	ENDIF
	
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º   MacintoshREAD contains clauses from SCREEN getorder   º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	READ CYCLE ;
		ACTIVATE _qne1bydf2() ;
		DEACTIVATE _qne1bydf6() ;
		MODAL
	
	RELEASE WINDOW _qne1byc3z
	
	#REGION 0
	
	SET READBORDER &rborder
	
	IF m.talkstat = "ON"
		SET TALK ON
	ENDIF
	IF m.compstat = "ON"
		SET COMPATIBLE ON
	ENDIF
	
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º             GETORDER/Macintosh Cleanup Code             º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	#REGION 1
	skipvar = .F.
	IF ordbut = 1
	   SET ORDER TO TAG(tagnum)
	ELSE
	   SET ORDER TO (m.startord)
	   m.tagnum = m.startord
	ENDIF
	SHOW GETS
	

CASE _WINDOWS

	
	#REGION 0
	REGIONAL m.currarea, m.talkstat, m.compstat
	
	IF SET("TALK") = "ON"
		SET TALK OFF
		m.talkstat = "ON"
	ELSE
		m.talkstat = "OFF"
	ENDIF
	m.compstat = SET("COMPATIBLE")
	SET COMPATIBLE FOXPLUS
	
	m.rborder = SET("READBORDER")
	SET READBORDER OFF
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º               Windows Window definitions                º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	IF NOT WEXIST("_qne1bydsi")
		DEFINE WINDOW _qne1bydsi ;
			AT  0.000, 0.000  ;
			SIZE 6.385,41.500 ;
			TITLE "Index Order" ;
			FONT "MS Sans Serif", 8 ;
			STYLE "B" ;
			FLOAT ;
			NOCLOSE ;
			SHADOW ;
			NOMINIMIZE ;
			DOUBLE ;
			COLOR RGB(,,,192,192,192)
		MOVE WINDOW _qne1bydsi CENTER
	ENDIF
	
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º         GETORDER/Windows Setup Code - SECTION 2         º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	#REGION 1
	skipvar = .T.
	
	IF TYPE("tagnum") = "U"
	   PUBLIC tagnum
	   tagnum = 1
	ENDIF
	
	m.startord = ORDER()
	m.startalias = ALIAS()
	
	SET ORDER TO 0
	numtag = 1
	DO WHILE "" <> TAG(numtag)
	   numtag = numtag + 1
	ENDDO
	
	DIMENSION idxtags(numtag-1)
	i = 1
	DO WHILE i <= numtag-1
	   idxtags[i] = TAG(i)
	   i = i + 1
	ENDDO
	SET ORDER TO (m.startord)
	
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º             GETORDER/Windows Screen Layout              º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	#REGION 1
	IF WVISIBLE("_qne1bydsi")
		ACTIVATE WINDOW _qne1bydsi SAME
	ELSE
		ACTIVATE WINDOW _qne1bydsi NOSHOW
	ENDIF
	@ 1.154,16.500 GET tagnum ;
		PICTURE "@^" ;
		FROM idxtags ;
		SIZE 1.538,23.400 ;
		DEFAULT 1 ;
		FONT "MS Sans Serif", 8
	@ 4.000,7.500 GET ordbut ;
		PICTURE "@*HT \!\<OK;\?\<Cancel" ;
		SIZE 1.538,10.667,2.167 ;
		DEFAULT 1 ;
		FONT "MS Sans Serif", 8 ;
		STYLE "B"
	@ 1.462,3.333 SAY "Index Order:"  ;
		FONT "MS Sans Serif", 8 ;
		STYLE "B"
	
	IF NOT WVISIBLE("_qne1bydsi")
		ACTIVATE WINDOW _qne1bydsi
	ENDIF
	
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º    WindowsREAD contains clauses from SCREEN getorder    º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	READ CYCLE ;
		ACTIVATE _qne1byecu() ;
		DEACTIVATE _qne1byecv() ;
		MODAL
	
	RELEASE WINDOW _qne1bydsi
	
	#REGION 0
	
	SET READBORDER &rborder
	
	IF m.talkstat = "ON"
		SET TALK ON
	ENDIF
	IF m.compstat = "ON"
		SET COMPATIBLE ON
	ENDIF
	
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º              GETORDER/Windows Cleanup Code              º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	#REGION 1
	skipvar = .F.
	IF ordbut = 1
	   SET ORDER TO TAG(tagnum)
	ELSE
	   SET ORDER TO (m.startord)
	   m.tagnum = m.startord
	ENDIF
	SHOW GETS
	

ENDCASE


*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BYBP5           Read Level Activate                º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º                                                         º
*       º From Platform:       MS-DOS                             º
*       º From Screen:         GETORDER                           º
*       º Called By:           READ Statement                     º
*       º Snippet Number:      1                                  º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1bybp5     && Read Level Activate
*
* Activate Code from screen: GETORDER
*
#REGION 1
SELECT (m.startalias)


*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BYBQT           Read Level Deactivate              º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º                                                         º
*       º From Platform:       MS-DOS                             º
*       º From Screen:         GETORDER                           º
*       º Called By:           READ Statement                     º
*       º Snippet Number:      2                                  º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1bybqt     && Read Level Deactivate
*
* Deactivate Code from screen: GETORDER
*
#REGION 1
?? CHR(7)
RETURN .F.


*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BYDF2           Read Level Activate                º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º                                                         º
*       º From Platform:       Macintosh                          º
*       º From Screen:         GETORDER                           º
*       º Called By:           READ Statement                     º
*       º Snippet Number:      3                                  º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1bydf2     && Read Level Activate
*
* Activate Code from screen: GETORDER
*
#REGION 1
SELECT (m.startalias)


*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BYDF6           Read Level Deactivate              º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º                                                         º
*       º From Platform:       Macintosh                          º
*       º From Screen:         GETORDER                           º
*       º Called By:           READ Statement                     º
*       º Snippet Number:      4                                  º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1bydf6     && Read Level Deactivate
*
* Deactivate Code from screen: GETORDER
*
#REGION 1
?? CHR(7)
RETURN .F.


*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BYECU           Read Level Activate                º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º                                                         º
*       º From Platform:       Windows                            º
*       º From Screen:         GETORDER                           º
*       º Called By:           READ Statement                     º
*       º Snippet Number:      5                                  º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1byecu     && Read Level Activate
*
* Activate Code from screen: GETORDER
*
#REGION 1
SELECT (m.startalias)


*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BYECV           Read Level Deactivate              º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º                                                         º
*       º From Platform:       Windows                            º
*       º From Screen:         GETORDER                           º
*       º Called By:           READ Statement                     º
*       º Snippet Number:      6                                  º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1byecv     && Read Level Deactivate
*
* Deactivate Code from screen: GETORDER
*
#REGION 1
?? CHR(7)
RETURN .F.
