*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º 02/09/94             PRTOPTS.SPR               22:22:42 º
*       º                                                         º
*       ÇÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¶
*       º                                                         º
*       º Author's Name                                           º
*       º                                                         º
*       º Copyright (c) 1994 Company Name                         º
*       º Address                                                 º
*       º City,     Zip                                           º
*       º                                                         º
*       º Description:                                            º
*       º This program was automatically generated by GENSCRN.    º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½

DO CASE
CASE _DOS OR _UNIX      && no UNIX records in screen

	
	#REGION 0
	REGIONAL m.currarea, m.talkstat, m.compstat
	
	IF SET("TALK") = "ON"
		SET TALK OFF
		m.talkstat = "ON"
	ELSE
		m.talkstat = "OFF"
	ENDIF
	m.compstat = SET("COMPATIBLE")
	SET COMPATIBLE FOXPLUS
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º                MS-DOS Window definitions                º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	IF NOT WEXIST("_qne1byq4d")
		DEFINE WINDOW _qne1byq4d ;
			FROM INT((SROW()-15)/2),INT((SCOL()-44)/2) ;
			TO INT((SROW()-15)/2)+14,INT((SCOL()-44)/2)+43 ;
			TITLE "Print Options" ;
			FLOAT ;
			NOCLOSE ;
			SHADOW ;
			NOMINIMIZE ;
			DOUBLE ;
			COLOR SCHEME 5
	ENDIF
	
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º          PRTOPTS/MS-DOS Setup Code - SECTION 2          º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	#REGION 1
	
	skipvar = .T.
	stemname = makealias(juststem(dbfname))
	SELECT (stemname)
	createrb = 0
	reptrb   = 3
	layoutrb = 0
	pdrivr   = 0
	lastpd   = 1
	
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º              PRTOPTS/MS-DOS Screen Layout               º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	#REGION 1
	IF WVISIBLE("_qne1byq4d")
		ACTIVATE WINDOW _qne1byq4d SAME
	ELSE
		ACTIVATE WINDOW _qne1byq4d NOSHOW
	ENDIF
	@ 7,8 GET pdrivrb ;
		PICTURE "@*RVN Use current printer driver;Use report printer driver;Use no printer driver" ;
		SIZE 1,30,0 ;
		DEFAULT 1
	@ 4,4 GET m.reptrb ;
		PICTURE "@*RVN \<Modify report;Printer \<setup;\<Print report" ;
		SIZE 1,17,0 ;
		DEFAULT 1 ;
		VALID _qne1byqky()
	@ 1,4 GET createrb ;
		PICTURE "@*RVN C\<reate report" ;
		SIZE 1,17,0 ;
		DEFAULT 1 ;
		VALID _qne1byqte()
	@ 2,8 GET layoutrb ;
		PICTURE "@*RVN Form layout;Columnar layout" ;
		SIZE 1,19,0 ;
		DEFAULT 1 ;
		DISABLE
	@ 11,8 GET okcancl ;
		PICTURE "@*HN \!OK;\?Cancel" ;
		SIZE 1,11,4 ;
		DEFAULT 1 ;
		VALID _qne1byqz5()
	
	IF NOT WVISIBLE("_qne1byq4d")
		ACTIVATE WINDOW _qne1byq4d
	ENDIF
	
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º     MS-DOSREAD contains clauses from SCREEN prtopts     º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	READ CYCLE ;
		SHOW _qne1bysau() ;
		MODAL
	
	RELEASE WINDOW _qne1byq4d
	
	#REGION 0
	IF m.talkstat = "ON"
		SET TALK ON
	ENDIF
	IF m.compstat = "ON"
		SET COMPATIBLE ON
	ENDIF
	
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º               PRTOPTS/MS-DOS Cleanup Code               º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	#REGION 1
	skipvar = .F.
	

CASE _MAC

	
	#REGION 0
	REGIONAL m.currarea, m.talkstat, m.compstat
	
	IF SET("TALK") = "ON"
		SET TALK OFF
		m.talkstat = "ON"
	ELSE
		m.talkstat = "OFF"
	ENDIF
	m.compstat = SET("COMPATIBLE")
	SET COMPATIBLE FOXPLUS
	
	m.rborder = SET("READBORDER")
	SET READBORDER OFF
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º              Macintosh Window definitions               º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	IF NOT WEXIST("_qne1bysjj")
		DEFINE WINDOW _qne1bysjj ;
			AT  0.000, 0.000  ;
			SIZE 17.615,43.000 ;
			TITLE "Print Options" ;
			FONT "Geneva", 10 ;
			FLOAT ;
			NOCLOSE ;
			SHADOW ;
			DOUBLE
		MOVE WINDOW _qne1bysjj CENTER
	ENDIF
	
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º        PRTOPTS/Macintosh Setup Code - SECTION 2         º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	#REGION 1
	
	skipvar = .T.
	stemname = makealias(juststem(dbfname))
	SELECT (stemname)
	createrb = 0
	reptrb   = 3
	layoutrb = 0
	pdrivr   = 0
	lastpd   = 1
	
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º             PRTOPTS/Macintosh Screen Layout             º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	#REGION 1
	IF WVISIBLE("_qne1bysjj")
		ACTIVATE WINDOW _qne1bysjj SAME
	ELSE
		ACTIVATE WINDOW _qne1bysjj NOSHOW
	ENDIF
	@ 9.385,7.000 GET pdrivrb ;
		PICTURE "@*RVN3 Use current printer driver;Use report printer driver;Use no printer driver" ;
		SIZE 1.308,26.167,0.000 ;
		DEFAULT 1 ;
		FONT "Geneva", 10 ;
		STYLE "T"
	@ 5.385,3.000 GET m.reptrb ;
		PICTURE "@*RVN3 \<Modify report;Printer \<setup;\<Print report" ;
		SIZE 1.308,15.333,0.000 ;
		DEFAULT 1 ;
		FONT "Geneva", 10 ;
		STYLE "T" ;
		VALID _qne1bysvw()
	@ 14.846,7.000 GET okcancl ;
		PICTURE "@*HN3 \!OK;\?Cancel" ;
		SIZE 1.462,11.000,4.000 ;
		DEFAULT 1 ;
		FONT "Geneva", 10 ;
		STYLE "B" ;
		VALID _qne1byt32()
	@ 1.077,3.000 GET createrb ;
		PICTURE "@*RVN3 C\<reate report" ;
		SIZE 1.308,15.000,0.000 ;
		DEFAULT 1 ;
		FONT "Geneva", 10 ;
		STYLE "T" ;
		VALID _qne1bytdy()
	@ 2.615,7.000 GET layoutrb ;
		PICTURE "@*RVN3 Form layout;Columnar layout" ;
		SIZE 1.308,17.333,0.000 ;
		DEFAULT 1 ;
		FONT "Geneva", 10 ;
		STYLE "T" ;
		DISABLE
	
	IF NOT WVISIBLE("_qne1bysjj")
		ACTIVATE WINDOW _qne1bysjj
	ENDIF
	
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º   MacintoshREAD contains clauses from SCREEN prtopts    º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	READ CYCLE ;
		SHOW _qne1bytqx() ;
		MODAL
	
	RELEASE WINDOW _qne1bysjj
	
	#REGION 0
	
	SET READBORDER &rborder
	
	IF m.talkstat = "ON"
		SET TALK ON
	ENDIF
	IF m.compstat = "ON"
		SET COMPATIBLE ON
	ENDIF
	
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º             PRTOPTS/Macintosh Cleanup Code              º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	#REGION 1
	skipvar = .F.
	

CASE _WINDOWS

	
	#REGION 0
	REGIONAL m.currarea, m.talkstat, m.compstat
	
	IF SET("TALK") = "ON"
		SET TALK OFF
		m.talkstat = "ON"
	ELSE
		m.talkstat = "OFF"
	ENDIF
	m.compstat = SET("COMPATIBLE")
	SET COMPATIBLE FOXPLUS
	
	m.rborder = SET("READBORDER")
	SET READBORDER OFF
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º               Windows Window definitions                º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	IF NOT WEXIST("_qne1bytzw")
		DEFINE WINDOW _qne1bytzw ;
			AT  0.000, 0.000  ;
			SIZE 17.615,43.000 ;
			TITLE "Print Options" ;
			FONT "MS Sans Serif", 8 ;
			STYLE "B" ;
			FLOAT ;
			NOCLOSE ;
			SHADOW ;
			NOMINIMIZE ;
			DOUBLE ;
			COLOR RGB(,,,192,192,192)
		MOVE WINDOW _qne1bytzw CENTER
	ENDIF
	
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º         PRTOPTS/Windows Setup Code - SECTION 2          º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	#REGION 1
	
	skipvar = .T.
	stemname = makealias(juststem(dbfname))
	SELECT (stemname)
	createrb = 0
	reptrb   = 3
	layoutrb = 0
	pdrivr   = 0
	lastpd   = 1
	
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º              PRTOPTS/Windows Screen Layout              º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	#REGION 1
	IF WVISIBLE("_qne1bytzw")
		ACTIVATE WINDOW _qne1bytzw SAME
	ELSE
		ACTIVATE WINDOW _qne1bytzw NOSHOW
	ENDIF
	@ 9.385,9.333 GET pdrivrb ;
		PICTURE "@*RVN Use current printer driver;Use report printer driver;Use no printer driver" ;
		SIZE 1.308,28.167,0.000 ;
		DEFAULT 1 ;
		FONT "MS Sans Serif", 8 ;
		STYLE "BT" ;
		COLOR ,,,,,,,,RGB(,,,192,192,192),RGB(,,,192,192,192)
	@ 5.385,5.333 GET m.reptrb ;
		PICTURE "@*RVN \<Modify report;Printer \<setup;\<Print report" ;
		SIZE 1.308,16.833,0.000 ;
		DEFAULT 1 ;
		FONT "MS Sans Serif", 8 ;
		STYLE "BT" ;
		VALID _qne1byued() ;
		COLOR ,,,,,,,,RGB(,,,192,192,192),RGB(,,,192,192,192)
	@ 1.077,5.333 GET createrb ;
		PICTURE "@*RVN C\<reate report" ;
		SIZE 1.308,16.833,0.000 ;
		DEFAULT 1 ;
		FONT "MS Sans Serif", 8 ;
		STYLE "BT" ;
		VALID _qne1byum4() ;
		COLOR ,,,,,,,,RGB(,,,192,192,192),RGB(,,,192,192,192)
	@ 2.538,9.333 GET layoutrb ;
		PICTURE "@*RVN Form layout;Columnar layout" ;
		SIZE 1.308,19.500,0.000 ;
		DEFAULT 1 ;
		FONT "MS Sans Serif", 8 ;
		STYLE "BT" ;
		DISABLE ;
		COLOR ,,,,,,,,RGB(,,,192,192,192),RGB(,,,192,192,192)
	@ 14.846,7.000 GET okcancl ;
		PICTURE "@*HN \!\<OK;\?\<Cancel" ;
		SIZE 1.538,11.000,4.000 ;
		DEFAULT 1 ;
		FONT "MS Sans Serif", 8 ;
		STYLE "B" ;
		VALID _qne1byus9()
	
	IF NOT WVISIBLE("_qne1bytzw")
		ACTIVATE WINDOW _qne1bytzw
	ENDIF
	
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º    WindowsREAD contains clauses from SCREEN prtopts     º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	READ CYCLE ;
		SHOW _qne1byv35() ;
		MODAL
	
	RELEASE WINDOW _qne1bytzw
	
	#REGION 0
	
	SET READBORDER &rborder
	
	IF m.talkstat = "ON"
		SET TALK ON
	ENDIF
	IF m.compstat = "ON"
		SET COMPATIBLE ON
	ENDIF
	
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º              PRTOPTS/Windows Cleanup Code               º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	#REGION 1
	skipvar = .F.
	

ENDCASE


*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BYQKY           m.reptrb VALID                     º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º From Platform:       MS-DOS                             º
*       º From Screen:         PRTOPTS,     Record Number:   10   º
*       º Variable:            m.reptrb                           º
*       º Called By:           VALID Clause                       º
*       º Object Type:         Radio Button                       º
*       º Snippet Number:      1                                  º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1byqky     &&  m.reptrb VALID
#REGION 1
DO CASE
CASE reptrb = 1
   lastpd = IIF(pdrivrb=0,lastpd,pdrivrb)
   pdrivrb = 0
   SHOW GET pdrivrb DISABLE
CASE reptrb = 2
   lastpd = IIF(pdrivrb=0,lastpd,pdrivrb)
   pdrivrb = 0
   SHOW GET pdrivrb DISABLE
CASE reptrb = 3
   pdrivrb = lastpd
   SHOW GET pdrivrb ENABLE
ENDCASE
createrb = 0
layoutrb = 0
SHOW GET layoutrb DISABLE
SHOW GET createrb


*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BYQTE           createrb VALID                     º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º From Platform:       MS-DOS                             º
*       º From Screen:         PRTOPTS,     Record Number:   11   º
*       º Variable:            createrb                           º
*       º Called By:           VALID Clause                       º
*       º Object Type:         Radio Button                       º
*       º Snippet Number:      2                                  º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1byqte     &&  createrb VALID
#REGION 1
IF createrb = 1
   reptrb   = 0
   pdrivrb  = 0
   layoutrb = 1
   SHOW GET reptrb
   SHOW GET layoutrb ENABLE
   SHOW GET pdrivrb  DISABLE
ENDIF


*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BYQZ5           okcancl VALID                      º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º From Platform:       MS-DOS                             º
*       º From Screen:         PRTOPTS,     Record Number:   13   º
*       º Variable:            okcancl                            º
*       º Called By:           VALID Clause                       º
*       º Object Type:         Push Button                        º
*       º Snippet Number:      3                                  º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1byqz5     &&  okcancl VALID
#REGION 1
IF okcancl = 1
   DO CASE
   CASE createrb = 1
      m.repname = UPPER(ALLTRIM(PUTFILE('Report form','','FRX','OK')))
      IF !EMPTY(m.repname)
         IF layoutrb = 1
            CREATE REPORT (m.repname) FROM (m.dbfname) FORM
         ELSE
            CREATE REPORT (m.repname) FROM (m.dbfname) COLUMN
         ENDIF
         MODIFY REPORT (m.repname)
      ENDIF
   CASE reptrb = 1
      MODIFY REPORT ?
   CASE reptrb = 2
      IF !regen
         mname = 'prtsetup.prg'
      ELSE
         mname = 'prtsetup.spr'
      ENDIF
      DO (mname)
   CASE reptrb = 3
      DO CASE
      CASE pdrivrb = 1
         DO putprt WITH ""
      CASE pdrivrb = 2
         DO putprt WITH "PDSETUP"
      CASE pdrivrb = 3
         old_driver = _PDRIVER
         _PDRIVER = ""
         DO putprt WITH ""
         _PDRIVER = old_driver
      ENDCASE
   ENDCASE
ELSE
   CLEAR READ
ENDIF




*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BYSAU           Read Level Show                    º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º                                                         º
*       º From Platform:       MS-DOS                             º
*       º From Screen:         PRTOPTS                            º
*       º Called By:           READ Statement                     º
*       º Snippet Number:      4                                  º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1bysau     && Read Level Show
PRIVATE currwind
STORE WOUTPUT() TO currwind
*
* Show Code from screen: PRTOPTS
*
#REGION 1
SHOW GET reptrb,2 DISABLE
IF NOT EMPTY(currwind)
	ACTIVATE WINDOW (currwind) SAME
ENDIF

*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BYSVW           m.reptrb VALID                     º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º From Platform:       Macintosh                          º
*       º From Screen:         PRTOPTS,     Record Number:   16   º
*       º Variable:            m.reptrb                           º
*       º Called By:           VALID Clause                       º
*       º Object Type:         Radio Button                       º
*       º Snippet Number:      5                                  º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1bysvw     &&  m.reptrb VALID
#REGION 1
DO CASE
CASE reptrb = 1
   lastpd = IIF(pdrivrb=0,lastpd,pdrivrb)
   pdrivrb = 0
   SHOW GET pdrivrb DISABLE
CASE reptrb = 2
   lastpd = IIF(pdrivrb=0,lastpd,pdrivrb)
   pdrivrb = 0
   SHOW GET pdrivrb DISABLE
CASE reptrb = 3
   pdrivrb = lastpd
   SHOW GET pdrivrb ENABLE
ENDCASE
createrb = 0
layoutrb = 0
SHOW GET layoutrb DISABLE
SHOW GET createrb


*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BYT32           okcancl VALID                      º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º From Platform:       Macintosh                          º
*       º From Screen:         PRTOPTS,     Record Number:   17   º
*       º Variable:            okcancl                            º
*       º Called By:           VALID Clause                       º
*       º Object Type:         Push Button                        º
*       º Snippet Number:      6                                  º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1byt32     &&  okcancl VALID
#REGION 1
IF okcancl = 1
   DO CASE
   CASE createrb = 1
      m.repname = UPPER(ALLTRIM(PUTFILE('Report form','','FRX','OK')))
      IF !EMPTY(m.repname)
         IF layoutrb = 1
            CREATE REPORT (m.repname) FROM (m.dbfname) FORM
         ELSE
            CREATE REPORT (m.repname) FROM (m.dbfname) COLUMN
         ENDIF
         MODIFY REPORT (m.repname)
      ENDIF
   CASE reptrb = 1
      MODIFY REPORT ?
   CASE reptrb = 2
      IF !regen
         mname = 'prtsetup.prg'
      ELSE
         mname = 'prtsetup.spr'
      ENDIF
      DO (mname)
   CASE reptrb = 3
      DO CASE
      CASE pdrivrb = 1
         DO putprt WITH ""
      CASE pdrivrb = 2
         DO putprt WITH "PDSETUP"
      CASE pdrivrb = 3
         old_driver = _PDRIVER
         _PDRIVER = ""
         DO putprt WITH ""
         _PDRIVER = old_driver
      ENDCASE
   ENDCASE
ELSE
   CLEAR READ
ENDIF




*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BYTDY           createrb VALID                     º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º From Platform:       Macintosh                          º
*       º From Screen:         PRTOPTS,     Record Number:   18   º
*       º Variable:            createrb                           º
*       º Called By:           VALID Clause                       º
*       º Object Type:         Radio Button                       º
*       º Snippet Number:      7                                  º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1bytdy     &&  createrb VALID
#REGION 1
IF createrb = 1
   reptrb   = 0
   pdrivrb  = 0
   layoutrb = 1
   SHOW GET reptrb
   SHOW GET layoutrb ENABLE
   SHOW GET pdrivrb  DISABLE
ENDIF


*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BYTQX           Read Level Show                    º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º                                                         º
*       º From Platform:       Macintosh                          º
*       º From Screen:         PRTOPTS                            º
*       º Called By:           READ Statement                     º
*       º Snippet Number:      8                                  º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1bytqx     && Read Level Show
PRIVATE currwind
STORE WOUTPUT() TO currwind
*
* Show Code from screen: PRTOPTS
*
#REGION 1
SHOW GET reptrb,2 DISABLE
IF NOT EMPTY(currwind)
	ACTIVATE WINDOW (currwind) SAME
ENDIF

*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BYUED           m.reptrb VALID                     º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º From Platform:       Windows                            º
*       º From Screen:         PRTOPTS,     Record Number:    3   º
*       º Variable:            m.reptrb                           º
*       º Called By:           VALID Clause                       º
*       º Object Type:         Radio Button                       º
*       º Snippet Number:      9                                  º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1byued     &&  m.reptrb VALID
#REGION 1
DO CASE
CASE reptrb = 1
   lastpd = IIF(pdrivrb=0,lastpd,pdrivrb)
   pdrivrb = 0
   SHOW GET pdrivrb DISABLE
CASE reptrb = 2
   lastpd = IIF(pdrivrb=0,lastpd,pdrivrb)
   pdrivrb = 0
   SHOW GET pdrivrb DISABLE
CASE reptrb = 3
   pdrivrb = lastpd
   SHOW GET pdrivrb ENABLE
ENDCASE
createrb = 0
layoutrb = 0
SHOW GET layoutrb DISABLE
SHOW GET createrb


*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BYUM4           createrb VALID                     º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º From Platform:       Windows                            º
*       º From Screen:         PRTOPTS,     Record Number:    4   º
*       º Variable:            createrb                           º
*       º Called By:           VALID Clause                       º
*       º Object Type:         Radio Button                       º
*       º Snippet Number:      10                                 º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1byum4     &&  createrb VALID
#REGION 1
IF createrb = 1
   reptrb   = 0
   pdrivrb  = 0
   layoutrb = 1
   SHOW GET reptrb
   SHOW GET layoutrb ENABLE
   SHOW GET pdrivrb  DISABLE
ENDIF


*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BYUS9           okcancl VALID                      º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º From Platform:       Windows                            º
*       º From Screen:         PRTOPTS,     Record Number:    6   º
*       º Variable:            okcancl                            º
*       º Called By:           VALID Clause                       º
*       º Object Type:         Push Button                        º
*       º Snippet Number:      11                                 º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1byus9     &&  okcancl VALID
#REGION 1
IF okcancl = 1
   DO CASE
   CASE createrb = 1
      m.repname = UPPER(ALLTRIM(PUTFILE('Report form','','FRX','OK')))
      IF !EMPTY(m.repname)
         IF layoutrb = 1
            CREATE REPORT (m.repname) FROM (m.dbfname) FORM
         ELSE
            CREATE REPORT (m.repname) FROM (m.dbfname) COLUMN
         ENDIF
         MODIFY REPORT (m.repname)
      ENDIF
   CASE reptrb = 1
      MODIFY REPORT ?
   CASE reptrb = 2
      IF !regen
         mname = 'prtsetup.prg'
      ELSE
         mname = 'prtsetup.spr'
      ENDIF
      DO (mname)
   CASE reptrb = 3
      DO CASE
      CASE pdrivrb = 1
         DO putprt WITH ""
      CASE pdrivrb = 2
         DO putprt WITH "PDSETUP"
      CASE pdrivrb = 3
         old_driver = _PDRIVER
         _PDRIVER = ""
         DO putprt WITH ""
         _PDRIVER = old_driver
      ENDCASE
   ENDCASE
ELSE
   CLEAR READ
ENDIF




*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BYV35           Read Level Show                    º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º                                                         º
*       º From Platform:       Windows                            º
*       º From Screen:         PRTOPTS                            º
*       º Called By:           READ Statement                     º
*       º Snippet Number:      12                                 º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1byv35     && Read Level Show
PRIVATE currwind
STORE WOUTPUT() TO currwind
*
* Show Code from screen: PRTOPTS
*
#REGION 1
SHOW GET reptrb,2 DISABLE
IF NOT EMPTY(currwind)
	ACTIVATE WINDOW (currwind) SAME
ENDIF


*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º  PRTOPTS/Windows Supporting Procedures and Functions    º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*

#REGION 1
PROCEDURE putprt
PARAMETERS reptparm

m.repname = UPPER(ALLTRIM(GETFILE('FRX|LBX','Report or label form')))
m.startrec = RECNO()
IF !EMPTY(m.repname)
   RELEASE m.repbut, m.repdest, m.okbut
   PUBLIC m.repbut, m.repdest, m.okbut

   IF !regen
      mname = 'getdest.prg'  && dialog box to get output destination
   ELSE
      mname = 'getdest.spr'
   ENDIF
   DO (mname)

   err_string = ON('ERROR')
   ON ERROR DO rpterror

   IF m.okbut = 1
      DO CASE
      CASE m.repbut = 1  && screen
         m.startwin = WONTOP()
         IF FILE(m.repname)
            REPORT FORM (m.repname) PREVIEW
         ELSE
            MODIFY REPORT (m.repname)
            IF FILE(m.repname)
               REPORT FORM (m.repname) PREVIEW
            ENDIF
         ENDIF

      CASE m.repbut = 2  && output to printer
         IF SYS(13) <> "READY"
            WAIT WINDOW "The printer is not ready."
         ELSE
            IF FILE(m.repname)
               WAIT WINDOW "Printing report..." NOWAIT
               REPORT FORM (m.repname) TO PRINT PROMPT NOCONSOLE &reptparm
               WAIT WINDOW "Report printed!" NOWAIT
               =INKEY(2,"HM")
               WAIT CLEAR
            ELSE
               MODIFY REPORT (m.repname)
               IF FILE(m.repname)
                  WAIT WINDOW "Printing report..." NOWAIT
                  REPORT FORM (m.repname) TO PRINT PROMPT NOCONSOLE &reptparm
                  WAIT WINDOW "Report printed!" NOWAIT
                  =INKEY(2,"HM")
                  WAIT CLEAR
               ENDIF
            ENDIF
         ENDIF

      CASE m.repbut = 3  && output to file
         m.repdest = ALLTRIM(m.repdest)
         IF !EMPTY(m.repdest)
            m.win_string = "Printing to "+m.repdest
            WAIT WINDOW m.win_string NOWAIT
            IF FILE(m.repname)
               REPORT FORM (m.repname) TO FILE (m.repdest) NOCONSOLE
            ELSE
               MODIFY REPORT (m.repname)
               IF FILE(m.repname)
                  REPORT FORM (m.repname) TO FILE (m.repdest) NOCONSOLE
               ENDIF
            ENDIF
         ENDIF
      ENDCASE
   ENDIF
ENDIF
IF TYPE('err_string') <> 'U'
   ON ERROR &err_string
ELSE
   ON ERROR
ENDIF

IF m.startrec <= RECCOUNT() AND m.startrec > 0
   GOTO m.startrec   && back to starting position
ELSE
   GOTO TOP
ENDIF


PROCEDURE rpterror
DO alert WITH "Error producing report.;The report form may not correspond to this database."
RETURN