*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º 02/09/94            PRTSETUP.SPR               22:21:57 º
*       º                                                         º
*       ÇÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¶
*       º                                                         º
*       º Author's Name                                           º
*       º                                                         º
*       º Copyright (c) 1994 Company Name                         º
*       º Address                                                 º
*       º City,     Zip                                           º
*       º                                                         º
*       º Description:                                            º
*       º This program was automatically generated by GENSCRN.    º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½

DO CASE
CASE _DOS OR _UNIX      && no UNIX records in screen

	
	#REGION 0
	REGIONAL m.currarea, m.talkstat, m.compstat
	
	IF SET("TALK") = "ON"
		SET TALK OFF
		m.talkstat = "ON"
	ELSE
		m.talkstat = "OFF"
	ENDIF
	m.compstat = SET("COMPATIBLE")
	SET COMPATIBLE FOXPLUS
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º                MS-DOS Window definitions                º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	IF NOT WEXIST("_qne1bxrgo")
		DEFINE WINDOW _qne1bxrgo ;
			FROM INT((SROW()-19)/2),INT((SCOL()-57)/2) ;
			TO INT((SROW()-19)/2)+18,INT((SCOL()-57)/2)+56 ;
			TITLE "Printing Destination" ;
			FLOAT ;
			NOCLOSE ;
			SHADOW ;
			NOMINIMIZE ;
			DOUBLE ;
			COLOR SCHEME 5
	ENDIF
	
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º         PRTSETUP/MS-DOS Setup Code - SECTION 2          º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	#REGION 1
	
	skipvar = .T.
	pfilname = SPACE(67)
	
	pdest = SET('PRINTER',1)
	IF ":" $ pdest
	   pdest = LEFT(pdest,AT(':',pdest)-1)
	ENDIF
	IF !INLIST(pdest,'PRN','LPT1','LPT2','LPT3','COM1','COM2','COM3')
	   pfilname = PADR(pdest,67)
	   pdest = 'File'
	ENDIF
	origdest = pdest
	prt_infile =pfilname
	
	IF SET('PRINT') = 'ON'
	   prtstat = 1
	ELSE
	   prtstat = 2
	ENDIF
	origprtstat = prtstat
	
	pdrivstup = IIF(LEN(_PDRIVER)=0,0,1)
	
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º              PRTSETUP/MS-DOS Screen Layout              º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	#REGION 1
	IF WVISIBLE("_qne1bxrgo")
		ACTIVATE WINDOW _qne1bxrgo SAME
	ELSE
		ACTIVATE WINDOW _qne1bxrgo NOSHOW
	ENDIF
	@ 1,2 TO 14,40
	@ 3,6 SAY "Print to:" ;
		SIZE 1,9, 0
	@ 1,6 SAY "Printer Setup:" ;
		SIZE 1,14, 0
	@ 2,17 GET pdest ;
		PICTURE "@^ File;PRN;LPT1;LPT2;LPT3;COM1;COM2;COM3" ;
		SIZE 3,16 ;
		DEFAULT "LPT1" ;
		VALID _qne1bxscy() ;
		COLOR SCHEME 5, 6
	@ 5,5 GET flist ;
		PICTURE "@*HN \<File..." ;
		SIZE 1,11,1 ;
		DEFAULT 1 ;
		VALID _qne1bxsgg()
	@ 7,4 GET pfilname ;
		SIZE 1,35 ;
		DEFAULT " " ;
		PICTURE "@3S67" ;
		VALID _qne1bxsoe()
	@ 10,4 GET prtstat ;
		PICTURE "@*RVN Print On;Print Off" ;
		SIZE 1,13,0 ;
		DEFAULT 2
	@ 10,36 GET _LMARGIN ;
		SIZE 1,2 ;
		DEFAULT " " ;
		PICTURE "@3 999" ;
		VALID _qne1bxstp()
	@ 11,36 GET _RMARGIN ;
		SIZE 1,2 ;
		DEFAULT " " ;
		PICTURE "@3 999" ;
		VALID _qne1bxsxh()
	@ 6,43 GET OKbut ;
		PICTURE "@*HT \!OK" ;
		SIZE 1,10,6 ;
		DEFAULT 1
	@ 8,43 GET CancBut ;
		PICTURE "@*HT \?Cancel" ;
		SIZE 1,10,1 ;
		DEFAULT 1
	@ 14,4 GET pdrivstup ;
		PICTURE "@*C Printer \<Driver Setup..." ;
		SIZE 1,27 ;
		DEFAULT 0 ;
		VALID _qne1bxt2a() ;
		DISABLE
	@ 10,22 SAY "Left Margin:" ;
		SIZE 1,12, 0
	@ 11,22 SAY "Right Margin:" ;
		SIZE 1,13, 0
	
	IF NOT WVISIBLE("_qne1bxrgo")
		ACTIVATE WINDOW _qne1bxrgo
	ENDIF
	
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º    MS-DOSREAD contains clauses from SCREEN prtsetup     º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	READ CYCLE ;
		DEACTIVATE _qne1bxt8z() ;
		SHOW _qne1bxt90() ;
		MODAL
	
	RELEASE WINDOW _qne1bxrgo
	
	#REGION 0
	IF m.talkstat = "ON"
		SET TALK ON
	ENDIF
	IF m.compstat = "ON"
		SET COMPATIBLE ON
	ENDIF
	
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º              PRTSETUP/MS-DOS Cleanup Code               º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	#REGION 1
	DO CASE
	CASE okbut = 1
	   SET PRINTER TO
	
	   IF prtstat = 1
	      SET PRINT ON
	   ELSE
	      SET PRINT OFF
	   ENDIF
	
	   pdest = ALLTRIM(UPPER(pdest))
	   DO CASE
	   CASE pdest = 'FILE'
	      IF !EMPTY(pfilname)
	         SET PRINTER TO (pfilname)
	      ELSE
	         SET PRINTER TO
	      ENDIF
	   OTHERWISE
	      pfilname = ''
	      SET PRINTER TO &pdest
	   ENDCASE
	CASE cancbut = 1
	   IF origprtstat = 1
	      SET PRINT ON
	   ELSE
	      SET PRINT OFF
	   ENDIF
	   pdest = origdest
	   pfilname = prt_infile
	ENDCASE
	skipvar = .F.
	

CASE _MAC

	
	#REGION 0
	REGIONAL m.currarea, m.talkstat, m.compstat
	
	IF SET("TALK") = "ON"
		SET TALK OFF
		m.talkstat = "ON"
	ELSE
		m.talkstat = "OFF"
	ENDIF
	m.compstat = SET("COMPATIBLE")
	SET COMPATIBLE FOXPLUS
	
	m.rborder = SET("READBORDER")
	SET READBORDER OFF
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º              Macintosh Window definitions               º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	IF NOT WEXIST("_qne1bxu40")
		DEFINE WINDOW _qne1bxu40 ;
			AT  0.000, 0.000  ;
			SIZE 17.000,57.000 ;
			TITLE "Printing Destination" ;
			FONT "Geneva", 10 ;
			FLOAT ;
			NOCLOSE ;
			SHADOW ;
			DOUBLE
		MOVE WINDOW _qne1bxu40 CENTER
	ENDIF
	
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º        PRTSETUP/Macintosh Setup Code - SECTION 2        º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	#REGION 1
	
	skipvar = .T.
	pfilname = SPACE(67)
	
	pdest = SET('PRINTER',1)
	IF ":" $ pdest
	   pdest = LEFT(pdest,AT(':',pdest)-1)
	ENDIF
	IF !INLIST(pdest,'PRN','LPT1','LPT2','LPT3','COM1','COM2','COM3')
	   pfilname = PADR(pdest,67)
	   pdest = 'File'
	ENDIF
	origdest = pdest
	prt_infile =pfilname
	
	IF SET('PRINT') = 'ON'
	   prtstat = 1
	ELSE
	   prtstat = 2
	ENDIF
	origprtstat = prtstat
	
	pdrivstup = IIF(LEN(_PDRIVER)=0,0,1)
	
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º            PRTSETUP/Macintosh Screen Layout             º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	#REGION 1
	IF WVISIBLE("_qne1bxu40")
		ACTIVATE WINDOW _qne1bxu40 SAME
	ELSE
		ACTIVATE WINDOW _qne1bxu40 NOSHOW
	ENDIF
	@ 2.769,2.500 TO 16.461,40.667 ;
		PEN 1, 8
	@ 3.538,9.000 SAY "Print to:"  ;
		FONT "Geneva", 10 ;
		STYLE "B"
	@ 1.231,3.000 SAY "Printer Setup:"  ;
		FONT "Geneva", 10 ;
		STYLE "B"
	@ 3.231,18.000 GET pdest ;
		PICTURE "@^3 File;PRN;LPT1;LPT2;LPT3;COM1;COM2;COM3" ;
		SIZE 1.462,19.833 ;
		DEFAULT "LPT1" ;
		FONT "Geneva", 10 ;
		VALID _qne1bxuni()
	@ 5.923,4.000 GET flist ;
		PICTURE "@*HN3 \<File..." ;
		SIZE 1.538,11.000,1.000 ;
		DEFAULT 1 ;
		FONT "Geneva", 10 ;
		STYLE "B" ;
		VALID _qne1bxut4()
	@ 8.231,4.833 GET pfilname ;
		SIZE 0.923,34.667 ;
		DEFAULT " " ;
		FONT "Geneva", 10 ;
		PICTURE "@3S67" ;
		VALID _qne1bxuy4()
	@ 10.846,4.000 GET prtstat ;
		PICTURE "@*RVN3 Print On;Print Off" ;
		SIZE 1.308,11.143,0.000 ;
		DEFAULT 2 ;
		FONT "Geneva", 10 ;
		STYLE "BT"
	@ 11.077,36.333 GET _LMARGIN ;
		SIZE 0.923,2.667 ;
		DEFAULT " " ;
		FONT "Geneva", 10 ;
		PICTURE "@3 999" ;
		VALID _qne1bxv59()
	@ 12.538,36.333 GET _RMARGIN ;
		SIZE 0.923,2.667 ;
		DEFAULT " " ;
		FONT "Geneva", 10 ;
		PICTURE "@3 999" ;
		VALID _qne1bxv7e()
	@ 2.769,43.500 GET OKbut ;
		PICTURE "@*HT3 \!OK" ;
		SIZE 1.538,10.000,6.000 ;
		DEFAULT 1 ;
		FONT "Geneva", 10 ;
		STYLE "B"
	@ 5.538,43.500 GET CancBut ;
		PICTURE "@*HT3 \?Cancel" ;
		SIZE 1.538,10.000,1.000 ;
		DEFAULT 1 ;
		FONT "Geneva", 10 ;
		STYLE "B"
	@ 14.692,4.000 GET pdrivstup ;
		PICTURE "@*C3 Printer \<Driver Setup..." ;
		SIZE 1.308,24.000 ;
		DEFAULT 0 ;
		FONT "Geneva", 10 ;
		STYLE "BT" ;
		VALID _qne1bxveb() ;
		DISABLE
	@ 11.000,22.000 SAY "Left Margin:"  ;
		FONT "Geneva", 10 ;
		STYLE "B"
	@ 12.462,22.000 SAY "Right Margin:"  ;
		FONT "Geneva", 10 ;
		STYLE "B"
	
	IF NOT WVISIBLE("_qne1bxu40")
		ACTIVATE WINDOW _qne1bxu40
	ENDIF
	
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º   MacintoshREAD contains clauses from SCREEN prtsetup   º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	READ CYCLE ;
		DEACTIVATE _qne1bxvm1() ;
		SHOW _qne1bxvm5() ;
		MODAL
	
	RELEASE WINDOW _qne1bxu40
	
	#REGION 0
	
	SET READBORDER &rborder
	
	IF m.talkstat = "ON"
		SET TALK ON
	ENDIF
	IF m.compstat = "ON"
		SET COMPATIBLE ON
	ENDIF
	
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º             PRTSETUP/Macintosh Cleanup Code             º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	#REGION 1
	DO CASE
	CASE okbut = 1
	   SET PRINTER TO
	
	   IF prtstat = 1
	      SET PRINT ON
	   ELSE
	      SET PRINT OFF
	   ENDIF
	
	   pdest = ALLTRIM(UPPER(pdest))
	   DO CASE
	   CASE pdest = 'FILE'
	      IF !EMPTY(pfilname)
	         SET PRINTER TO (pfilname)
	      ELSE
	         SET PRINTER TO
	      ENDIF
	   OTHERWISE
	      pfilname = ''
	      SET PRINTER TO &pdest
	   ENDCASE
	CASE cancbut = 1
	   IF origprtstat = 1
	      SET PRINT ON
	   ELSE
	      SET PRINT OFF
	   ENDIF
	   pdest = origdest
	   pfilname = prt_infile
	ENDCASE
	skipvar = .F.
	

CASE _WINDOWS

	
	#REGION 0
	REGIONAL m.currarea, m.talkstat, m.compstat
	
	IF SET("TALK") = "ON"
		SET TALK OFF
		m.talkstat = "ON"
	ELSE
		m.talkstat = "OFF"
	ENDIF
	m.compstat = SET("COMPATIBLE")
	SET COMPATIBLE FOXPLUS
	
	m.rborder = SET("READBORDER")
	SET READBORDER OFF
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º               Windows Window definitions                º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	IF NOT WEXIST("_qne1bxwbc")
		DEFINE WINDOW _qne1bxwbc ;
			AT  0.000, 0.000  ;
			SIZE 17.000,57.000 ;
			TITLE "Printing Destination" ;
			FONT "MS Sans Serif", 8 ;
			STYLE "B" ;
			FLOAT ;
			NOCLOSE ;
			SHADOW ;
			NOMINIMIZE ;
			DOUBLE ;
			COLOR RGB(,,,192,192,192)
		MOVE WINDOW _qne1bxwbc CENTER
	ENDIF
	
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º         PRTSETUP/Windows Setup Code - SECTION 2         º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	#REGION 1
	
	skipvar = .T.
	pfilname = SPACE(67)
	
	pdest = SET('PRINTER',1)
	IF ":" $ pdest
	   pdest = LEFT(pdest,AT(':',pdest)-1)
	ENDIF
	IF !INLIST(pdest,'PRN','LPT1','LPT2','LPT3','COM1','COM2','COM3')
	   pfilname = PADR(pdest,67)
	   pdest = 'File'
	ENDIF
	origdest = pdest
	prt_infile =pfilname
	
	IF SET('PRINT') = 'ON'
	   prtstat = 1
	ELSE
	   prtstat = 2
	ENDIF
	origprtstat = prtstat
	
	pdrivstup = IIF(LEN(_PDRIVER)=0,0,1)
	
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º             PRTSETUP/Windows Screen Layout              º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	#REGION 1
	IF WVISIBLE("_qne1bxwbc")
		ACTIVATE WINDOW _qne1bxwbc SAME
	ELSE
		ACTIVATE WINDOW _qne1bxwbc NOSHOW
	ENDIF
	@ 2.462,2.500 TO 16.154,40.667 ;
		PEN 1, 8
	@ 3.462,8.667 SAY "Print to:"  ;
		FONT "MS Sans Serif", 8 ;
		STYLE "B"
	@ 1.000,3.000 SAY "Printer Setup:"  ;
		FONT "MS Sans Serif", 8 ;
		STYLE "B"
	@ 3.231,17.833 GET pdest ;
		PICTURE "@^ File;PRN;LPT1;LPT2;LPT3;COM1;COM2;COM3" ;
		SIZE 1.538,19.800 ;
		DEFAULT "LPT1" ;
		FONT "MS Sans Serif", 8 ;
		VALID _qne1bxwvo()
	@ 5.615,4.000 GET flist ;
		PICTURE "@*HN \<File..." ;
		SIZE 1.538,11.000,1.000 ;
		DEFAULT 1 ;
		FONT "MS Sans Serif", 8 ;
		STYLE "B" ;
		VALID _qne1bxwy6()
	@ 7.692,4.333 GET pfilname ;
		SIZE 1.000,34.500 ;
		DEFAULT " " ;
		FONT "MS Sans Serif", 8 ;
		STYLE "B" ;
		PICTURE "@3S67" ;
		VALID _qne1bxx6f()
	@ 10.538,4.000 GET prtstat ;
		PICTURE "@*RVN Print On;Print Off" ;
		SIZE 1.308,12.333,0.000 ;
		DEFAULT 2 ;
		FONT "MS Sans Serif", 8 ;
		STYLE "BT" ;
		COLOR ,,,,,,,,RGB(,,,192,192,192),RGB(,,,192,192,192)
	@ 10.692,35.167 GET _LMARGIN ;
		SIZE 1.000,2.667 ;
		DEFAULT " " ;
		FONT "MS Sans Serif", 8 ;
		STYLE "B" ;
		PICTURE "@3 999" ;
		VALID _qne1bxxci()
	@ 12.154,35.167 GET _RMARGIN ;
		SIZE 1.000,2.667 ;
		DEFAULT " " ;
		FONT "MS Sans Serif", 8 ;
		STYLE "B" ;
		PICTURE "@3 999" ;
		VALID _qne1bxxgh()
	@ 2.462,43.500 GET OKbut ;
		PICTURE "@*HT \!OK" ;
		SIZE 1.538,10.000,6.000 ;
		DEFAULT 1 ;
		FONT "MS Sans Serif", 8 ;
		STYLE "B"
	@ 4.769,43.500 GET CancBut ;
		PICTURE "@*HT \?Cancel" ;
		SIZE 1.538,10.000,1.000 ;
		DEFAULT 1 ;
		FONT "MS Sans Serif", 8 ;
		STYLE "B"
	@ 14.231,4.000 GET pdrivstup ;
		PICTURE "@*C Printer \<Driver Setup..." ;
		SIZE 1.308,26.333 ;
		DEFAULT 0 ;
		FONT "MS Sans Serif", 8 ;
		STYLE "BT" ;
		VALID _qne1bxxno() ;
		DISABLE
	@ 10.692,20.833 SAY "Left Margin:"  ;
		FONT "MS Sans Serif", 8 ;
		STYLE "B"
	@ 12.154,20.833 SAY "Right Margin:"  ;
		FONT "MS Sans Serif", 8 ;
		STYLE "B"
	
	IF NOT WVISIBLE("_qne1bxwbc")
		ACTIVATE WINDOW _qne1bxwbc
	ENDIF
	
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º    WindowsREAD contains clauses from SCREEN prtsetup    º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	READ CYCLE ;
		DEACTIVATE _qne1bxxty() ;
		SHOW _qne1bxxu1() ;
		MODAL
	
	RELEASE WINDOW _qne1bxwbc
	
	#REGION 0
	
	SET READBORDER &rborder
	
	IF m.talkstat = "ON"
		SET TALK ON
	ENDIF
	IF m.compstat = "ON"
		SET COMPATIBLE ON
	ENDIF
	
	
	*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
	*       º                                                         º
	*       º              PRTSETUP/Windows Cleanup Code              º
	*       º                                                         º
	*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
	*
	
	#REGION 1
	DO CASE
	CASE okbut = 1
	   SET PRINTER TO
	
	   IF prtstat = 1
	      SET PRINT ON
	   ELSE
	      SET PRINT OFF
	   ENDIF
	
	   pdest = ALLTRIM(UPPER(pdest))
	   DO CASE
	   CASE pdest = 'FILE'
	      IF !EMPTY(pfilname)
	         SET PRINTER TO (pfilname)
	      ELSE
	         SET PRINTER TO
	      ENDIF
	   OTHERWISE
	      pfilname = ''
	      SET PRINTER TO &pdest
	   ENDCASE
	CASE cancbut = 1
	   IF origprtstat = 1
	      SET PRINT ON
	   ELSE
	      SET PRINT OFF
	   ENDIF
	   pdest = origdest
	   pfilname = prt_infile
	ENDCASE
	skipvar = .F.
	

ENDCASE


*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BXSCY           pdest VALID                        º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º From Platform:       MS-DOS                             º
*       º From Screen:         PRTSETUP,     Record Number:    5  º
*       º Variable:            pdest                              º
*       º Called By:           VALID Clause                       º
*       º Object Type:         Popup                              º
*       º Snippet Number:      1                                  º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1bxscy     &&  pdest VALID
#REGION 1
IF UPPER(pdest) = 'FILE'
   _CUROBJ = 3
ENDIF
SHOW GETS


*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BXSGG           flist VALID                        º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º From Platform:       MS-DOS                             º
*       º From Screen:         PRTSETUP,     Record Number:    6  º
*       º Variable:            flist                              º
*       º Called By:           VALID Clause                       º
*       º Object Type:         Push Button                        º
*       º Snippet Number:      2                                  º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1bxsgg     &&  flist VALID
#REGION 1
IF flist = 1
   origfile = pfilname
   pfilname = GETFILE('','Print to:')
   IF EMPTY(pfilname)
      pfilname = origfile
   ENDIF
ENDIF
pfilname = UPPER(PADR(pfilname,67))
IF !EMPTY(pfilname)
   pdest = 'File'
ENDIF
SHOW GETS


*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BXSOE           pfilname VALID                     º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º From Platform:       MS-DOS                             º
*       º From Screen:         PRTSETUP,     Record Number:    7  º
*       º Variable:            pfilname                           º
*       º Called By:           VALID Clause                       º
*       º Object Type:         Field                              º
*       º Snippet Number:      3                                  º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1bxsoe     &&  pfilname VALID
#REGION 1
pfilname = PADR(UPPER(LTRIM(pfilname)),67)
IF !EMPTY(pfilname)
   pdest = 'File'
ENDIF
SHOW GETS


*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BXSTP           _LMARGIN VALID                     º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º From Platform:       MS-DOS                             º
*       º From Screen:         PRTSETUP,     Record Number:    9  º
*       º Variable:            _LMARGIN                           º
*       º Called By:           VALID Clause                       º
*       º Object Type:         Field                              º
*       º Snippet Number:      4                                  º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1bxstp     &&  _LMARGIN VALID
#REGION 1
_LMARGIN = MAX(0,_LMARGIN)
SHOW GETS


*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BXSXH           _RMARGIN VALID                     º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º From Platform:       MS-DOS                             º
*       º From Screen:         PRTSETUP,     Record Number:   10  º
*       º Variable:            _RMARGIN                           º
*       º Called By:           VALID Clause                       º
*       º Object Type:         Field                              º
*       º Snippet Number:      5                                  º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1bxsxh     &&  _RMARGIN VALID
#REGION 1
_RMARGIN = MIN(_RMARGIN,255)
SHOW GETS


*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BXT2A           pdrivstup VALID                    º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º From Platform:       MS-DOS                             º
*       º From Screen:         PRTSETUP,     Record Number:   13  º
*       º Variable:            pdrivstup                          º
*       º Called By:           VALID Clause                       º
*       º Object Type:         Check Box                          º
*       º Snippet Number:      6                                  º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1bxt2a     &&  pdrivstup VALID
#REGION 1
DO (_GENPD) WITH 1,"?"
IF LEN(_PDSETUP) = 0
   pdrivstup = 0
ELSE
   pdrivstup = 1
ENDIF
SHOW GET pdrivstup


*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BXT8Z           Read Level Deactivate              º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º                                                         º
*       º From Platform:       MS-DOS                             º
*       º From Screen:         PRTSETUP                           º
*       º Called By:           READ Statement                     º
*       º Snippet Number:      7                                  º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1bxt8z     && Read Level Deactivate
*
* Deactivate Code from screen: PRTSETUP
*
#REGION 1
?? CHR(7)
RETURN .F.


*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BXT90           Read Level Show                    º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º                                                         º
*       º From Platform:       MS-DOS                             º
*       º From Screen:         PRTSETUP                           º
*       º Called By:           READ Statement                     º
*       º Snippet Number:      8                                  º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1bxt90     && Read Level Show
PRIVATE currwind
STORE WOUTPUT() TO currwind
*
* Show Code from screen: PRTSETUP
*
#REGION 1
IF UPPER(pdest) = 'FILE'
   SHOW GET pfilname ENABLE
   IF EMPTY(pfilname)
      SHOW GET okbut DISABLE
   ELSE
      SHOW GET okbut ENABLE
   ENDIF
ELSE
   SHOW GET pfilname DISABLE
   SHOW GET okbut ENABLE
ENDIF

IF NOT EMPTY(currwind)
	ACTIVATE WINDOW (currwind) SAME
ENDIF

*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BXUNI           pdest VALID                        º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º From Platform:       Macintosh                          º
*       º From Screen:         PRTSETUP,     Record Number:   20  º
*       º Variable:            pdest                              º
*       º Called By:           VALID Clause                       º
*       º Object Type:         Popup                              º
*       º Snippet Number:      9                                  º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1bxuni     &&  pdest VALID
#REGION 1
IF UPPER(pdest) = 'FILE'
   _CUROBJ = 3
ENDIF
SHOW GETS


*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BXUT4           flist VALID                        º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º From Platform:       Macintosh                          º
*       º From Screen:         PRTSETUP,     Record Number:   21  º
*       º Variable:            flist                              º
*       º Called By:           VALID Clause                       º
*       º Object Type:         Push Button                        º
*       º Snippet Number:      10                                 º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1bxut4     &&  flist VALID
#REGION 1
IF flist = 1
   origfile = pfilname
   pfilname = GETFILE('','Print to:')
   IF EMPTY(pfilname)
      pfilname = origfile
   ENDIF
ENDIF
pfilname = UPPER(PADR(pfilname,67))
IF !EMPTY(pfilname)
   pdest = 'File'
ENDIF
SHOW GETS


*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BXUY4           pfilname VALID                     º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º From Platform:       Macintosh                          º
*       º From Screen:         PRTSETUP,     Record Number:   22  º
*       º Variable:            pfilname                           º
*       º Called By:           VALID Clause                       º
*       º Object Type:         Field                              º
*       º Snippet Number:      11                                 º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1bxuy4     &&  pfilname VALID
#REGION 1
pfilname = PADR(UPPER(LTRIM(pfilname)),67)
IF !EMPTY(pfilname)
   pdest = 'File'
ENDIF
SHOW GETS


*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BXV59           _LMARGIN VALID                     º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º From Platform:       Macintosh                          º
*       º From Screen:         PRTSETUP,     Record Number:   24  º
*       º Variable:            _LMARGIN                           º
*       º Called By:           VALID Clause                       º
*       º Object Type:         Field                              º
*       º Snippet Number:      12                                 º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1bxv59     &&  _LMARGIN VALID
#REGION 1
_LMARGIN = MAX(0,_LMARGIN)
SHOW GETS


*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BXV7E           _RMARGIN VALID                     º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º From Platform:       Macintosh                          º
*       º From Screen:         PRTSETUP,     Record Number:   25  º
*       º Variable:            _RMARGIN                           º
*       º Called By:           VALID Clause                       º
*       º Object Type:         Field                              º
*       º Snippet Number:      13                                 º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1bxv7e     &&  _RMARGIN VALID
#REGION 1
_RMARGIN = MIN(_RMARGIN,255)
SHOW GETS


*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BXVEB           pdrivstup VALID                    º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º From Platform:       Macintosh                          º
*       º From Screen:         PRTSETUP,     Record Number:   28  º
*       º Variable:            pdrivstup                          º
*       º Called By:           VALID Clause                       º
*       º Object Type:         Check Box                          º
*       º Snippet Number:      14                                 º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1bxveb     &&  pdrivstup VALID
#REGION 1
DO (_GENPD) WITH 1,"?"
IF LEN(_PDSETUP) = 0
   pdrivstup = 0
ELSE
   pdrivstup = 1
ENDIF
SHOW GET pdrivstup


*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BXVM1           Read Level Deactivate              º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º                                                         º
*       º From Platform:       Macintosh                          º
*       º From Screen:         PRTSETUP                           º
*       º Called By:           READ Statement                     º
*       º Snippet Number:      15                                 º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1bxvm1     && Read Level Deactivate
*
* Deactivate Code from screen: PRTSETUP
*
#REGION 1
?? CHR(7)
RETURN .F.


*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BXVM5           Read Level Show                    º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º                                                         º
*       º From Platform:       Macintosh                          º
*       º From Screen:         PRTSETUP                           º
*       º Called By:           READ Statement                     º
*       º Snippet Number:      16                                 º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1bxvm5     && Read Level Show
PRIVATE currwind
STORE WOUTPUT() TO currwind
*
* Show Code from screen: PRTSETUP
*
#REGION 1
IF UPPER(pdest) = 'FILE'
   SHOW GET pfilname ENABLE
   IF EMPTY(pfilname)
      SHOW GET okbut DISABLE
   ELSE
      SHOW GET okbut ENABLE
   ENDIF
ELSE
   SHOW GET pfilname DISABLE
   SHOW GET okbut ENABLE
ENDIF

IF NOT EMPTY(currwind)
	ACTIVATE WINDOW (currwind) SAME
ENDIF

*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BXWVO           pdest VALID                        º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º From Platform:       Windows                            º
*       º From Screen:         PRTSETUP,     Record Number:   37  º
*       º Variable:            pdest                              º
*       º Called By:           VALID Clause                       º
*       º Object Type:         Popup                              º
*       º Snippet Number:      17                                 º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1bxwvo     &&  pdest VALID
#REGION 1
IF UPPER(pdest) = 'FILE'
   _CUROBJ = 3
ENDIF
SHOW GETS


*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BXWY6           flist VALID                        º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º From Platform:       Windows                            º
*       º From Screen:         PRTSETUP,     Record Number:   38  º
*       º Variable:            flist                              º
*       º Called By:           VALID Clause                       º
*       º Object Type:         Push Button                        º
*       º Snippet Number:      18                                 º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1bxwy6     &&  flist VALID
#REGION 1
IF flist = 1
   origfile = pfilname
   pfilname = GETFILE('','Print to:')
   IF EMPTY(pfilname)
      pfilname = origfile
   ENDIF
ENDIF
pfilname = UPPER(PADR(pfilname,67))
IF !EMPTY(pfilname)
   pdest = 'File'
ENDIF
SHOW GETS


*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BXX6F           pfilname VALID                     º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º From Platform:       Windows                            º
*       º From Screen:         PRTSETUP,     Record Number:   39  º
*       º Variable:            pfilname                           º
*       º Called By:           VALID Clause                       º
*       º Object Type:         Field                              º
*       º Snippet Number:      19                                 º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1bxx6f     &&  pfilname VALID
#REGION 1
pfilname = PADR(UPPER(LTRIM(pfilname)),67)
IF !EMPTY(pfilname)
   pdest = 'File'
ENDIF
SHOW GETS


*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BXXCI           _LMARGIN VALID                     º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º From Platform:       Windows                            º
*       º From Screen:         PRTSETUP,     Record Number:   41  º
*       º Variable:            _LMARGIN                           º
*       º Called By:           VALID Clause                       º
*       º Object Type:         Field                              º
*       º Snippet Number:      20                                 º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1bxxci     &&  _LMARGIN VALID
#REGION 1
_LMARGIN = MAX(0,_LMARGIN)
SHOW GETS


*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BXXGH           _RMARGIN VALID                     º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º From Platform:       Windows                            º
*       º From Screen:         PRTSETUP,     Record Number:   42  º
*       º Variable:            _RMARGIN                           º
*       º Called By:           VALID Clause                       º
*       º Object Type:         Field                              º
*       º Snippet Number:      21                                 º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1bxxgh     &&  _RMARGIN VALID
#REGION 1
_RMARGIN = MIN(_RMARGIN,255)
SHOW GETS


*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BXXNO           pdrivstup VALID                    º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º From Platform:       Windows                            º
*       º From Screen:         PRTSETUP,     Record Number:   45  º
*       º Variable:            pdrivstup                          º
*       º Called By:           VALID Clause                       º
*       º Object Type:         Check Box                          º
*       º Snippet Number:      22                                 º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1bxxno     &&  pdrivstup VALID
#REGION 1
DO (_GENPD) WITH 1,"?"
IF LEN(_PDSETUP) = 0
   pdrivstup = 0
ELSE
   pdrivstup = 1
ENDIF
SHOW GET pdrivstup


*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BXXTY           Read Level Deactivate              º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º                                                         º
*       º From Platform:       Windows                            º
*       º From Screen:         PRTSETUP                           º
*       º Called By:           READ Statement                     º
*       º Snippet Number:      23                                 º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1bxxty     && Read Level Deactivate
*
* Deactivate Code from screen: PRTSETUP
*
#REGION 1
?? CHR(7)
RETURN .F.


*       ÖÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ·
*       º                                                         º
*       º _QNE1BXXU1           Read Level Show                    º
*       º                                                         º
*       º Function Origin:                                        º
*       º                                                         º
*       º                                                         º
*       º From Platform:       Windows                            º
*       º From Screen:         PRTSETUP                           º
*       º Called By:           READ Statement                     º
*       º Snippet Number:      24                                 º
*       º                                                         º
*       ÓÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ½
*
FUNCTION _qne1bxxu1     && Read Level Show
PRIVATE currwind
STORE WOUTPUT() TO currwind
*
* Show Code from screen: PRTSETUP
*
#REGION 1
IF UPPER(pdest) = 'FILE'
   SHOW GET pfilname ENABLE
   IF EMPTY(pfilname)
      SHOW GET okbut DISABLE
   ELSE
      SHOW GET okbut ENABLE
   ENDIF
ELSE
   SHOW GET pfilname DISABLE
   SHOW GET okbut ENABLE
ENDIF

IF NOT EMPTY(currwind)
	ACTIVATE WINDOW (currwind) SAME
ENDIF